# fly.toml app configuration file generated for sunbot on 2023-12-25T18:40:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sunbot"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[[mounts]]
  source = "sunbot_data"
  destination = "/data"
  auto_extend_size_threshold = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
